version: '3.4'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Administrator*123
    ports:
      - "1434:1433"
  collectio.presentation:
    depends_on:
      - sql-server
    environment:
      - ASPNETCORE_IdentityServer__Authority=http://localhost:80
      - ASPNETCORE_IdentityServer__RequireHttpsMetadata=false
      - ASPNETCORE_ConnectionStrings__DefaultConnection=Server=sql-server;Database=Collectio;User Id=sa;Password=Administrator*123
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro